# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 449f3171c068b8292d8e0ea197d645a911c88fad4c631e23047d9e0e4aa6ba9f6c592aebad3a814454adebb44716755c67cde5c03eb26ed7252903a8395fd95d

test:
  secret_key_base: b2d82f6340c0faa40932c51a9cd9a73e9f7a4be383e035654fd241d5ef7d671546aca5b3e50343b6ea329fdbd70d125ddf853574546923d88d60d1eed78bfa44

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
